### PR TITLE
Add a Write API call

### PR DESCRIPTION
**Pull request by RKrahl**
IDS internally has WRITE, ARCHIVE; and RESTORE deferred operations.  While ARCHIVE and RESTORE may explicitely be triggered by corresponding API calls, there is no such call for WRITE in the current ids.server version.  There are use cases that could benefit from being able to trigger WRITE externally.  This PR adds the missing call.

~~Note that the implementation uses the current locking mechanism and thus there is a conflict with the new locking mechanism from PR #59. As soon as either PR gets merged into master, the other one would need to be amended, which I would be happy to care about.~~

### CODE REVIEW

**Comment by RKrahl** [comment]
I now merged the master branch including the new locking mechanism.

**Comment by stuartpullinger** [comment]
Hi Rolf,

Thanks for contributing this change. I am taking a conservative approach to adding new features to the code. Please could you elaborate on the use cases for this feature?

**Comment by RKrahl** [comment]
One possible use case could be the data ingest into IDS.

At the ICAT F2F meeting in March 2015 I gave a talk on [IDS versus Direct File Access to Storage](https://icatproject.org/wp-content/uploads/2015/04/direct-ids.pdf).  I presented some considerations whether it is possible to directly access the files in the storage managed by ids.server by other processes and how to prevent concurrent and possibly conflicting access using file system locking in the plugin.

I considered among others the "ingest by writing directly into main storage" as use case and  concluded that with the current IDS version (as of March 2015) there is no way to protect against race conditions.  I furthermore noted that further improvement would require changes in ids.server and to the plugin API.  In the meanwhile, we did a redesign of the internal locking mechanism in ids.server.  While useful on its own, this redesign was also an important precondition for these "further improvement" that I had in mind in March 2015.

Now, we would need two more ingredients to make ingest by writing directly into main storage safe and efficient: a change in the plugin API, see [my mail to the list](https://groups.google.com/forum/#!topic/icatgroup/48ujBhk5Nqg), and the Write API call in ids.server proposed in this PR.

**Comment by RKrahl** [comment]
@stuartpullinger following the discussion in the meeting today, I'd like to make the start and ask you to have a look on the changes.  If you don't see any issues, I would merge this PR into master.

**Comment by stuartpullinger** [comment]
Thanks Rolf. Just one comment: In [af5a8cc line 2141](https://github.com/icatproject/ids.server/pull/67/commits/af5a8ccf39f0145b6c6d5a8ac4951b5e40d449f1), why create a DataNotOnlineException and not an AlreadyLockedException? It seems to me that the latter would be a better description of the problem. The AlreadyLockedException would need a message describing or pointing to the DataSet which is locked. This would need to be added in the lockmanager.lock method (and the AlreadyLockedException definition changed in the same file). I imagining a case where some process goes wrong and a single lock holds up other work - it would help to know what it is.

What do you think?

**Comment by RKrahl** [comment]
We must distinguish between exceptions that are thrown and caught internally at the one hand and exceptions that are returned to the client in web service calls at the other hand.  The latter must be derived from `IdsException` because they must embed an HTTP status code and be jsonized by `IdsExceptionMapper`. `AlreadyLockedException` is heavily used internally and caught in most of the cases, see for instance in the `FiniteStateMachine` for the typical use. I don't think it would be a good idea to use an `IdsException` in that way.

What could be done, is to add a new exception, say `DataNotAvailableException` that extends `IdsException` and map `AlreadyLockedException` to that one in web service calls. In any case, this is not related to this PR on the Write API call. It has been discussed in #59 but finally been rejected to keep it simple. I don't mind to revive the idea, but then it must be done consistently in all web service calls, `AlreadyLockedException` is also mapped to `DataNotOnlineException` in `delete()`, `getData()`, `getLink()`, and `put()`. So we should open another issue on this if desired.

**Pull request merged**
