### PR TITLE
Implement the new locking mechanism

### PR DESCRIPTION
**Pull request by RKrahl**
**Note:** This is not yet ready, there is some tidying to be done before merging into master.  In particular, the `test` directory and the `NOTES.rst` file do not belong into the final sources and should be removed.  But otherwise it seem to be ready and I wanted to give you the opportunity to review the code and to test it before finalizing it, so I open this PR now.

This is the new locking mechanism as [discussed F2F in Copenhagen](https://icatproject.org/wp-content/uploads/2016/04/ids-locking.pdf).  In Copenhagen, I also made the proposal to add a plugin call so that the internal locking can be combined with file system locks to also synchronize with external processes.  This additional option could be coded on top of this PR later on.

There are some things to note:

- `LockManager`: this is the central new class to manage the locks and to obtain the locks from.
- Scope: Locks are always set on whole datasets, even in the case of storageUnit datafile.  This was also the case in the old implementation.  It would make things rather complicated to change this, so I suggest to leave it as is.
- `AlreadyLockedException`: the `LockManager.lock()` method throws this exception if it can't obtain the lock because there is already another lock.  For the moment, the definition of the exception class is nested inside the `LockManager`.  There might be a better better place though.
- `getServiceStatus`: This web service call used to return something like:
  ```
  {'opsQueue': [{'request': 'WRITE_THEN_ARCHIVE_REQUESTED', 'data': '911105/911235 (ESNF/12100409-ST/1.1-P/test_race_upload_archive)'}], 'lockCount': 1, 'lockedIds': [911235]}
  ```
  Note the field `lockedIds` which is a list of all datasets ids having a lock set.  The new implementation now returns:
  ```
  {'opsQueue': [{'request': 'ARCHIVE_REQUESTED', 'data': '911105/911238 (ESNF/12100409-ST/1.1-P/test_race_upload_archive)'}], 'lockCount': 1, 'locks': [{'id': 911238, 'count': 2, 'type': 'SHARED'}]}
  ```
  The field `lockedIds` has been renamed to `locks`.  The entries in this list now have the three attributes `id`, `type`, and `count`, where `id` is the dataset id, `type` is either `SHARED` or `EXCLUSIVE`, and `count` is the number of locks on this dataset.  I think this additional information might be useful.  But if compatibility with the old behavior is needed, it's essentially one line of code to change this.
- Exceptions: Web service calls may now fail because the corresponding data is locked.  They will throw a `DataNotOnlineException` for the moment.  While the definition of the error condition might not quite match this case, from the client's point of view it's the same: it is a temporary failure and the client may retry the same request later on.  We may add another more specific error class for this purpose.
  Note that the delete web service call used to throw `BadRequestException` in this case in the old implementation.  I'd say, this was just wrong.
- Testing: I didn't add any junit tests.  First because I didn't learned the ropes of the test setup by now and can't run the test here either.  Secondly because it would be rather difficult to formulate suitable test cases in the first place.  In most situations, the effect of the locking can only be verified by checking the ids.log in Glassfish, but it is largely invisible on the client side.  I added a provisional `test` directory with some Python scripts, just to document things.  But this is certainly not the right place to put it and should be removed again before merging.

### CODE REVIEW

**Comment by RKrahl** [comment]
My testing is done so far, everything looks fine now from my side.  I now removed all the temporary stuff that was only meant to document this PR but not to be included into the merge into master.  (Obviously, you can still checkout 3c9c46d to have a look at this complementary stuff.)  I'd consider this PR ready to merge now.

**Comment by fisherab** [comment]
I will give it a go now

**Comment by RKrahl** [comment]
@fisherab Steve, the PR has conflicts with your latest changes.  Do you want me to resolve them or do you want to care about them?

**Comment by fisherab** [comment]
Rolf,

I would be very pleased for you to resolve the conflicts. I made a mistake on my first attempt and decided to start again. The LockManager itself is checked in.

Steve

**Pull request merged**
